production:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET'] %>
  endpoint:
  secure: true
  private:
  expires: 

development:
  access_key_id: 
  secret_access_key: 
  bucket: 
  endpoint:
  secure:
  private:
  expires: 
